pullRequests.frequency = "7 days"
pullRequests.customLabels = ["dependencies", "scala"]
pullRequests.grouping = [
  {
    name = "patch-updates"
    title = "Patch dependency updates"
    filter = [{ version = "patch" }]
  }
]

updates.limit = 5
updatePullRequests = "always"
commits.message = "chore(deps): update ${artifactName} to ${nextVersion}"
