package org.galaxio.gatling.storage

import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

class JdbcStorageBackendSpec extends AnyWordSpec with Matchers {

  "JdbcStorageBackend" should {

    "reject tableName with SQL injection payload" in {
      val thrown = intercept[IllegalArgumentException] {
        JdbcStorageBackend("jdbc:recording:", tableName = "results; DROP TABLE results; --")
      }
      thrown.getMessage should include("Invalid tableName")
    }

    "reject empty tableName" in {
      val thrown = intercept[IllegalArgumentException] {
        JdbcStorageBackend("jdbc:recording:", tableName = "")
      }
      thrown.getMessage should include("Invalid tableName")
    }

    "reject tableName starting with a digit" in {
      val thrown = intercept[IllegalArgumentException] {
        JdbcStorageBackend("jdbc:recording:", tableName = "123bad")
      }
      thrown.getMessage should include("Invalid tableName")
    }

    "accept a valid tableName" in {
      noException should be thrownBy JdbcStorageBackend("jdbc:recording:", tableName = "my_results_2024")
    }

    "close the result set when load fails" in {
      val driver = new JdbcTestSupport.RecordingJdbcDriver("jdbc:recording:", Seq("not-json"))

      JdbcTestSupport.withRegisteredDriver(driver) {
        val backend = JdbcStorageBackend("jdbc:recording:storage")

        intercept[Exception] {
          backend.load()
        }
      }

      driver.state.resultSetCloseCount.get() shouldBe 1
      driver.state.statementCloseCount.get() shouldBe 2
      driver.state.connectionCloseCount.get() shouldBe 1
    }

    "initialize the table only once per backend instance" in {
      val driver = new JdbcTestSupport.RecordingJdbcDriver("jdbc:recording:")

      JdbcTestSupport.withRegisteredDriver(driver) {
        val backend = JdbcStorageBackend("jdbc:recording:storage")

        backend.save(Seq(Map[String, Any]("user" -> "alice")))
        backend.load()
        backend.clear()
      }

      driver.state.ddlCount.get() shouldBe 1
      driver.state.executeBatchCount.get() shouldBe 1
      driver.state.queryCount.get() shouldBe 1
      driver.state.statementCloseCount.get() shouldBe 3
      driver.state.preparedStatementCloseCount.get() shouldBe 1
      driver.state.connectionCloseCount.get() shouldBe 3
    }

    "initialize the table before clearing a fresh backend" in {
      val driver = new JdbcTestSupport.RecordingJdbcDriver("jdbc:recording:")

      JdbcTestSupport.withRegisteredDriver(driver) {
        val backend = JdbcStorageBackend("jdbc:recording:storage")

        noException should be thrownBy backend.clear()
      }

      driver.state.ddlCount.get() shouldBe 1
      driver.state.statementCloseCount.get() shouldBe 2
      driver.state.connectionCloseCount.get() shouldBe 1
    }

    "emit IDENTITY DDL (PostgreSQL/H2 standard)" in {
      val driver = new JdbcTestSupport.RecordingJdbcDriver("jdbc:recording:")

      JdbcTestSupport.withRegisteredDriver(driver) {
        JdbcStorageBackend("jdbc:recording:storage").clear()
      }

      driver.state.lastDdl should include("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    }

  }

}
