addSbtPlugin("com.github.sbt"       % "sbt-ci-release"        % "1.11.2")
addSbtPlugin("io.gatling"           % "gatling-sbt"           % "4.18.0")
addSbtPlugin("com.github.sbt.junit" % "sbt-jupiter-interface" % "0.17.0")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"          % "2.5.6")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"         % "2.4.4")
